version: "3.9"

services:
  file_service:
    build:
      context: ./file_service
    ports:
      - "8000:8000"
    volumes:
      - ./file_service/storage:/app/storage
    depends_on:
      - parser_service
    environment:
      - PARSER_HOST=parser_service
      - PARSER_PORT=50051

  parser_service:
    build:
      context: ./parser_service
    ports:
      - "50051:50051"
    volumes:
      - ./parser_service:/app
