services:
  file_service:
    build:
      context: ./file_service
    ports:
      - "8001:8002"
    volumes:
      - ./file_service/storage:/app/storage
    depends_on:
      - parser_service
    environment:
      - PARSER_HOST=parser_service
      - PARSER_PORT=50051

  parser_service:
    build:
      context: ./parser_service
    ports:
      - "50051:50051"
    volumes:
      - ./parser_service:/app

  summarizer_service:
    build:
      context: ./summarizer_service
    ports:
      - "8000:8003"
      - "50052:50052"

  worker_service:
    build: ./worker_service
    depends_on:
      - rabbitmq
      - summarizer_service


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5673"
      - "15673:15673"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

