version: "3.9"

services:
  file_service:
    build:
      context: ./file_service
    ports:
      - "8001:8000"
    volumes:
      - ./file_service/storage:/app/storage
    depends_on:
      - parser_service
    environment:
      - PARSER_HOST=parser_service
      - PARSER_PORT=50051

  parser_service:
    build:
      context: ./parser_service
    ports:
      - "50051:50051"
    volumes:
      - ./parser_service:/app

  worker_service:
    build: ./summarization_worker
    depends_on:
      - rabbitmq
      - summarizer_service
      - redis


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

