services:
  file_service:
    build:
      context: ./file_service
    ports:
      - "8001:8002"
    volumes:
      - ./file_service/storage:/app/storage
    depends_on:
      - parser_service
      - auth_service
    environment:
      - PARSER_HOST=parser_service
      - PARSER_PORT=50051

  parser_service:
    build:
      context: ./parser_service
    ports:
      - "50051:50051"
    volumes:
      - ./parser_service:/app

  processing_service:
    build:
      context: processing_service
    ports:
      - "8000:8003"
      - "50052:50052"

  worker_service:
    build: ./worker_service
    depends_on:
      - rabbitmq
      - processing_service
        
  auth_service:
    build: ./auth_service
    container_name: resumate-auth-service
    restart: unless-stopped
    ports:
      - "8005:8005"


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC (traces + metrics)
      - "4318:4318"   # OTLP HTTP (optional)
      - "8889:8889"   # Prometheus scrape endpoint

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"   # Jaeger UI

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"


