# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: parser.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'parser.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cparser.proto\x12\x06parser\"<\n\x12ParseResumeRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"#\n\x13ParseResumeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2V\n\x0cResumeParser\x12\x46\n\x0bParseResume\x12\x1a.parser.ParseResumeRequest\x1a\x1b.parser.ParseResumeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'parser_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARSERESUMEREQUEST']._serialized_start=24
  _globals['_PARSERESUMEREQUEST']._serialized_end=84
  _globals['_PARSERESUMERESPONSE']._serialized_start=86
  _globals['_PARSERESUMERESPONSE']._serialized_end=121
  _globals['_RESUMEPARSER']._serialized_start=123
  _globals['_RESUMEPARSER']._serialized_end=209
# @@protoc_insertion_point(module_scope)
