# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: summarizer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'summarizer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10summarizer.proto\x12\nsummarizer\"*\n\nSummaryJob\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x1d\n\nSummaryAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32I\n\nSummarizer\x12;\n\tSummarize\x12\x16.summarizer.SummaryJob\x1a\x16.summarizer.SummaryAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'summarizer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMMARYJOB']._serialized_start=32
  _globals['_SUMMARYJOB']._serialized_end=74
  _globals['_SUMMARYACK']._serialized_start=76
  _globals['_SUMMARYACK']._serialized_end=105
  _globals['_SUMMARIZER']._serialized_start=107
  _globals['_SUMMARIZER']._serialized_end=180
# @@protoc_insertion_point(module_scope)
