services:
  kong:
    image: kong:3.4
    container_name: kong
    restart: unless-stopped
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    volumes:
      - "./kong/kong.yml:/usr/local/kong/kong.yml"

    ports:
      - "8000:8000"   # Proxy (client-facing)
      - "8001:8001"   # Admin (HTTP)
      - "8444:8444"   # Admin (HTTPS)
