name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (parser_service)
        run: |
          cd parser_service
          pip install -r requirements.txt

      - name: Run unit tests (parser_service)
        run: |
          cd parser_service
          pytest